networks:
    application:
        name: application
        driver: bridge
services:
    app:
        container_name: nome-do-seu-servico-app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            args:
                PHP_VERSION: 8.4-fpm-bullseye
                HOST_UID: "${UID:-1000}"
                HOST_GID: "${GID:-1000}"
            target: app
        environment:
            - XDG_CONFIG_HOME=/var/www/app/storage
        volumes:
            - './:/var/www/app'
            - /var/www/app/vendor
            - /var/www/app/node_modules
        ports:
            - "80:80"

        networks:
            - application
        depends_on:
            - redis
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - application
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    postgres:
        image: 'postgres:15-alpine'
        ports:
            - '${DB_PORT:-5432}:5432'
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
            POSTGRES_SCHEMA: '${DB_SCHEMA}'
        volumes:
            - 'app-postgres:/var/lib/postgresql/data'
            - './docker/postgres:/docker-entrypoint-initdb.d'
        networks:
            - application
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            retries: 3
            timeout: 5s

volumes:
    app-postgres:
            driver: local
    redis:
        driver: local